import React, { useState } from 'react';
import { saveAs } from 'file-saver';

const ImageOutput = ({ images }) => {
  const [selectedImage, setSelectedImage] = useState(0);

  const downloadImage = (imageData) => {
    const byteCharacters = atob(imageData);
    const byteNumbers = new Array(byteCharacters.length);
    
    for (let i = 0; i < byteCharacters.length; i++) {
      byteNumbers[i] = byteCharacters.charCodeAt(i);
    }
    
    const byteArray = new Uint8Array(byteNumbers);
    const blob = new Blob([byteArray], { type: 'image/png' });
    saveAs(blob, 'aibuddies-generated-image.png');
  };

  return (
    <div className="space-y-4">
      {images.length > 1 && (
        <div className="flex space-x-2 overflow-x-auto pb-2">
          {images.map((img, index) => (
            <button
              key={index}
              className={`p-1 rounded-md ${
                selectedImage === index 
                  ? 'ring-2 ring-indigo-500' 
                  : 'hover:bg-gray-100'
              }`}
              onClick={() => setSelectedImage(index)}
            >
              <img 
                src={`data:image/png;base64,${img}`} 
                alt={`Generated variant ${index + 1}`} 
                className="w-16 h-16 object-cover rounded-md"
              />
            </button>
          ))}
        </div>
      )}
      
      <div className="relative">
        <img 
          src={`data:image/png;base64,${images[selectedImage]}`} 
          alt="Generated by AIBUDDIES" 
          className="w-full h-auto rounded-lg shadow-md"
        />
        
        <button
          onClick={() => downloadImage(images[selectedImage])}
          className="absolute top-4 right-4 bg-white rounded-full p-2 shadow-md hover:bg-gray-50"
          aria-label="Download image"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
        </button>
      </div>
    </div>
  );
};

export default ImageOutput;
